# Generated by Django 2.2.2 on 2019-06-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190606_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submitdata',
            new_name='User_Info',
        ),
    ]
